name: release

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
              node-version: 20

        - name: Install dependencies
          run: npm install

        - name: Run build
          run: npm run build

        - name: Archive production artifacts
          run: zip -r dist.zip dist/

        - uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./dist.zip
            asset_name: dist.zip
            asset_content_type: application/zip