name: release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        browser: [chrome, firefox]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and zip extension
        id: build
        run: |
          if [ "${{ matrix.browser }}" == "firefox" ]; then
            npm run zip:firefox
            # 実際の出力ファイルを見つける
            ZIP_PATH=$(find .output -name "chatsnavi-*-firefox.zip" -type f)
            # ファイル名を取得
            ZIP_NAME=$(basename $ZIP_PATH)
            echo "ZIP_PATH=$ZIP_PATH" >> $GITHUB_OUTPUT
            echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
          else
            npm run zip
            # 実際の出力ファイルを見つける
            ZIP_PATH=$(find .output -name "chatsnavi-*-chrome.zip" -type f)
            # ファイル名を取得
            ZIP_NAME=$(basename $ZIP_PATH)
            echo "ZIP_PATH=$ZIP_PATH" >> $GITHUB_OUTPUT
            echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.build.outputs.ZIP_PATH }}
          asset_name: ${{ steps.build.outputs.ZIP_NAME }}
          asset_content_type: application/zip
